mysql_root_password: avatar123
mysql_databases:
  - name: notes
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: notesapp
    host: "%"
    password: avatar123
    priv: "notes.*:ALL"